name : Node Continuous Integration
on: push
jobs: 
  build-node:
    name: Build and Run Node project  
    runs-on: ubuntu-latest
    steps:
      - run: node --version
        name: check node version
      - run: npm --version
        name: check npm version
      - uses: actions/checkout@v3
        name: Checkout code from GitHub
      - run: npm install
        name: Install NPM packages
      - run: node app.js
        name: Run Node Application
      - run: python install
      - run: python --version